name: biketrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.1
  flutter_local_notifications: ^19.2.1
  supabase_flutter: ^2.9.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  